<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LoginApiTest extends TestCase
{
    use RefreshDatabase;
    
    public function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      
      //テストユーザーの作成
      $this->user = factory(User::class)->create();
      
    }
    
    /**
     * @test
     */
    
    public function should_登録済みのユーザーを認証してreturnするぞ()
    {
      $response = $this->json('POST', route('login'), [
          'email' => $this->user->email,
          'password' => 'password'
      ]);
  
  
      $response
          ->assertStatus(200)
          ->assertJson(['name' => $this->user->name]);
  
      $this->assertAuthenticatedAs($this->user);
    }
}
